# Generated by Django 5.1.6 on 2025-03-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_4',
            field=models.TextField(blank=True),
        ),
    ]
