# Generated by Django 5.1.6 on 2025-03-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_question_answer_1_alter_question_answer_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='media/exams_files/', verbose_name='file'),
        ),
    ]
