# Generated by Django 5.1.6 on 2025-03-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='exam_files/', verbose_name='file'),
        ),
    ]
