# Generated by Django 5.1.6 on 2025-03-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_thema_type_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='thema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_thema', to='exam.thema'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_category', to='exam.type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_category', to='exam.category'),
        ),
    ]
