# Generated by Django 5.1.6 on 2025-03-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_thema_question_type_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_description',
            field=models.TextField(blank=True),
        ),
    ]
