# Generated by Django 5.1.6 on 2025-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_question_answer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
