# Generated by Django 5.1.6 on 2025-03-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.CharField(max_length=600),
        ),
    ]
