# Generated by Django 5.1.6 on 2025-03-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0004_alter_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
