# Generated by Django 5.1.6 on 2025-05-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0005_message_phone_number_message_url_review_type_and_more'),
        ('fahrschule_muller', '0006_message_phone_number_message_url_and_more'),
    ]

    operations = [
    ]
