# Generated by Django 5.1.6 on 2025-05-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0009_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
