# Generated by Django 5.1.6 on 2025-05-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0010_subscriber_is_valid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='TelegramSubscriber',
        ),
    ]
