# Generated by Django 5.1.6 on 2025-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0011_rename_subscriber_telegramsubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Lernmittel-Set Motorrad', max_length=255)),
                ('image', models.FileField(blank=True, upload_to='order_files/', verbose_name='img')),
                ('article_number', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
