# Generated by Django 5.1.6 on 2025-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0012_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='full_description',
            field=models.TextField(blank=True, default='', verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Короткое описание для карточки товара'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
