# Generated by Django 5.1.6 on 2025-05-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0013_orderitem_full_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Запрос с сайта', 'verbose_name_plural': 'Запросы с сайта'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='telegramsubscriber',
            options={'verbose_name': 'Учетная запись Telegram', 'verbose_name_plural': 'Учетные записи Telegram'},
        ),
        migrations.AddField(
            model_name='message',
            name='connection_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='form_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='article_number',
            field=models.CharField(default='', max_length=50, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.FileField(blank=True, upload_to='order_files/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название товара'),
        ),
    ]
