# Generated by Django 5.1.6 on 2025-05-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0014_alter_message_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fahrschule_muller.orderitemtype', verbose_name='Тип товара'),
        ),
    ]
