# Generated by Django 5.1.6 on 2025-05-29 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0015_orderitemtype_orderitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahrschule_muller.orderitemtype', verbose_name='Тип товара'),
        ),
    ]
