# Generated by Django 5.1.6 on 2025-06-13 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0016_alter_orderitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, choices=[('anmeldung', 'Anmeldung')], max_length=100, verbose_name='Имя формы')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Источник URL')),
                ('anrede', models.CharField(blank=True, max_length=20, verbose_name='Обращение (Herr/Frau)')),
                ('vorname', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('nachname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('anschrift', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('plz', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('geburtsort', models.CharField(blank=True, max_length=100, verbose_name='Место рождения')),
                ('geburtsdatum', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('fristablauf', models.DateField(blank=True, null=True, verbose_name='Срок окончания')),
                ('form_message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_sending_to_admin', models.DateTimeField(blank=True, null=True)),
                ('result_of_sending_to_admin', models.TextField(blank=True, default='')),
            ],
        ),
    ]
