# Generated by Django 5.1.6 on 2025-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0017_anmeldung'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsfCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('lessons_duration', models.IntegerField(verbose_name='Длительность одного занятия в часах')),
                ('lesson_1_date', models.DateTimeField(verbose_name='Дата/время первого занятия')),
                ('lesson_2_date', models.DateTimeField(verbose_name='Дата/время второго занятия')),
                ('lesson_3_date', models.DateTimeField(verbose_name='Дата/время третьего занятия')),
                ('lesson_4_date', models.DateTimeField(verbose_name='Дата/время четвертого занятия')),
                ('fahrproben', models.TextField(blank=True, default='', max_length=100, verbose_name='Fahrproben')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='anmeldung',
            name='form_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя формы'),
        ),
    ]
