# Generated by Django 5.1.6 on 2025-06-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0018_asfcourse_alter_anmeldung_form_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anmeldung',
            options={'verbose_name': 'ASF заявка', 'verbose_name_plural': 'ASF заявки'},
        ),
        migrations.AlterModelOptions(
            name='asfcourse',
            options={'verbose_name': 'ASF Курс', 'verbose_name_plural': 'ASF Курсы'},
        ),
        migrations.AddField(
            model_name='anmeldung',
            name='course',
            field=models.CharField(blank=True, max_length=255, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='anmeldung',
            name='fuhrerschein',
            field=models.CharField(blank=True, max_length=255, verbose_name='Категория водительских прав'),
        ),
        migrations.AlterField(
            model_name='asfcourse',
            name='lessons_duration',
            field=models.IntegerField(default=135, verbose_name='Длительность одного занятия в минутах'),
        ),
    ]
