# Generated by Django 5.1.6 on 2025-06-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0020_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
