# Generated by Django 5.1.6 on 2025-06-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule_muller', '0021_sitesettings_address_alter_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=50, unique=True)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Текст сайта',
                'verbose_name_plural': 'Тексты сайта',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройка сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
    ]
